version: "3"
services:

  database:
    container_name: postgres
    image: postgres:latest
    environment:
     - "POSTGRES_USER=postgresComentarios"
     - "POSTGRES_PASSWORD=Bdsse1cu@000"
     - "POSTGRES_DB=api-comentarios"
    ports:
      - 5433:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - mynetwork


  pgAdmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    environment:
      - "PGADMIN_DEFAULT_EMAIL=andree@gmail.com"
      - "PGADMIN_DEFAULT_PASSWORD=teste123"
    ports:
      - 15432:80
    networks:
      - mynetwork

  appcomentarios:
    container_name: api-comentarios
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      - database

    ports:
      - 8080:8080
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  pg-data:

